export const MOCK_INTEGRATIONS = [
  {
    id: "crowdstrike",
    name: "CrowdStrike Falcon",
    status: "Connected",
    lastIngestion: "2 mins ago",
    events: "1.2M",
    freshness: "Excellent",
    categories: ["Endpoint", "Security Events"],
    ocsfCoverage: "92%",
    lastSync: "Today, 11:54 AM",
    assetsDiscovered: 4200,
    vulnsDiscovered: 154,
  },
  {
    id: "sentinel",
    name: "Microsoft Sentinel",
    status: "Connected",
    lastIngestion: "5 mins ago",
    events: "3.4M",
    freshness: "Excellent",
    categories: ["Security Events", "Cloud"],
    ocsfCoverage: "88%",
    lastSync: "Today, 11:51 AM",
    assetsDiscovered: 0,
    vulnsDiscovered: 0,
  },
  {
    id: "aws",
    name: "AWS Security Hub",
    status: "Warning",
    lastIngestion: "14 mins ago",
    events: "89K",
    freshness: "Degraded",
    categories: ["Cloud", "Assets", "Vulnerabilities"],
    ocsfCoverage: "78%",
    lastSync: "Today, 11:42 AM",
    assetsDiscovered: 1250,
    vulnsDiscovered: 312,
  },
  {
    id: "okta",
    name: "Okta",
    status: "Connected",
    lastIngestion: "1 min ago",
    events: "450K",
    freshness: "Excellent",
    categories: ["IAM", "Security Events"],
    ocsfCoverage: "96%",
    lastSync: "Today, 11:55 AM",
    assetsDiscovered: 0,
    vulnsDiscovered: 0,
  },
  {
    id: "qualys",
    name: "Qualys",
    status: "Connected",
    lastIngestion: "1 hour ago",
    events: "12K",
    freshness: "Good",
    categories: ["Vulnerabilities", "Assets"],
    ocsfCoverage: "85%",
    lastSync: "Today, 10:56 AM",
    assetsDiscovered: 3800,
    vulnsDiscovered: 12400,
  },
  {
    id: "wiz",
    name: "Wiz",
    status: "Disconnected",
    lastIngestion: "2 days ago",
    events: "0",
    freshness: "Stale",
    categories: ["Cloud", "Vulnerabilities"],
    ocsfCoverage: "0%",
    lastSync: "Sep 28, 04:00 PM",
    assetsDiscovered: 980,
    vulnsDiscovered: 450,
  }
];

export const MOCK_REMEDIATIONS = [
  {
    id: "rem-1",
    action: "Patch Payment API (CVE-2026-8192)",
    asset: "payment-api-prod",
    risk: "Critical",
    currentLoss: 4200000,
    cost: 300000,
    riskReduction: 3500000,
    roi: 11.67,
    owner: "Payments Eng",
    deadline: "Oct 04",
    status: "Open"
  },
  {
    id: "rem-2",
    action: "Fix exposed S3 bucket",
    asset: "s3-customer-data",
    risk: "High",
    currentLoss: 1400000,
    cost: 50000,
    riskReduction: 1200000,
    roi: 24.0,
    owner: "Cloud Sec",
    deadline: "Oct 02",
    status: "In Progress"
  },
  {
    id: "rem-3",
    action: "Rotate compromised credentials",
    asset: "admin-svc-account",
    risk: "High",
    currentLoss: 900000,
    cost: 20000,
    riskReduction: 800000,
    roi: 40.0,
    owner: "IAM Team",
    deadline: "Sep 30",
    status: "Open"
  },
  {
    id: "rem-4",
    action: "Patch internet-facing VPN",
    asset: "vpn-gateway-us",
    risk: "Medium",
    currentLoss: 2200000,
    cost: 150000,
    riskReduction: 1800000,
    roi: 12.0,
    owner: "Net Sec",
    deadline: "Oct 10",
    status: "Open"
  }
];

export const MOCK_TIMELINE = [
  {
    id: "t1",
    time: "09:42",
    event: "CVE-2026-8192 detected",
    asset: "System-wide scan",
    change: "New vulnerability ingested via Qualys",
    riskImpact: "Analysis pending",
    financialImpact: null,
    status: "Detection"
  },
  {
    id: "t2",
    time: "10:03",
    event: "Payment API identified as affected",
    asset: "payment-api-prod",
    change: "Asset context correlated",
    riskImpact: "Criticality: High",
    financialImpact: null,
    status: "Analysis"
  },
  {
    id: "t3",
    time: "10:11",
    event: "Internet exposure confirmed",
    asset: "payment-api-prod",
    change: "Network path to internet verified via AWS",
    riskImpact: "Exposure probability increased",
    financialImpact: null,
    status: "Analysis"
  },
  {
    id: "t4",
    time: "10:16",
    event: "Expected Loss updated",
    asset: "payment-api-prod",
    change: "Monte Carlo simulation completed",
    riskImpact: "Risk Increased",
    financialImpact: "+₹18L Expected Loss",
    status: "Risk Increase"
  },
  {
    id: "t5",
    time: "11:45",
    event: "Patch deployment initiated",
    asset: "payment-api-prod",
    change: "Ticket assigned to Payments Eng",
    riskImpact: "Remediation pending",
    financialImpact: null,
    status: "Remediation"
  },
  {
    id: "t6",
    time: "12:14",
    event: "Patch deployed",
    asset: "payment-api-prod",
    change: "Verification scan passed",
    riskImpact: "Vulnerability closed",
    financialImpact: null,
    status: "Remediation"
  },
  {
    id: "t7",
    time: "12:18",
    event: "Expected Loss reduced",
    asset: "payment-api-prod",
    change: "Model recalibrated",
    riskImpact: "Risk Decreased",
    financialImpact: "-₹16L Expected Loss (₹18L → ₹2L residual)",
    status: "Risk Reduction"
  }
];
